mmee/urls.py
from django.urls import include, re_path, path
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from wagtail.admin import urls as wagtailadmin_urls
from kdl_ldap.signal_handlers import \
    register_signal_handlers as kdl_ldap_register_signal_hadlers
import os.path

kdl_ldap_register_signal_hadlers()

admin.autodiscover()

urlpatterns = [
    path('taggit/', include('taggit_selectize.urls')),
    path('admin/', admin.site.urls),

    re_path('wagtail/', include(wagtailadmin_urls)),

    # re_path('documents/', include('wagtail.documents.urls')),

    path('', include('photos.urls')),
    # path('search/', include('haystack.urls')),

    # we temporarily by pass wagtail to show search interface on home page
    # nest increment we can implement search with proper wagtail page
    path('', RedirectView.as_view(url='/photos/', permanent=False)),

    re_path('', include('wagtail.core.urls')),

]

# -----------------------------------------------------------------------------
# Django Debug Toolbar URLS
# -----------------------------------------------------------------------------
try:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns = [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
except ImportError:
    pass

# -----------------------------------------------------------------------------
# Static file DEBUGGING
# -----------------------------------------------------------------------------
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL + 'images/',
        document_root=os.path.join(settings.MEDIA_ROOT, 'images')
    )
#     urlpatterns += [
#         re_path(r'^favicon\.ico$',
#           RedirectView.as_view(
#               url=settings.STATIC_URL + 'myapp/images/favicon.ico'))
#     ]

photos/urls.py
# from django.conf import settings
from django.contrib import admin
from django.urls import path   # include, re_path
from photos.views.html import PhotoSearchView, PhotoDetailView, PhotoCreateView
from photos.views.json import ApiPhotoSearchView
from django.views.generic.base import TemplateView

admin.autodiscover()

API_VERSION = '1.0'
API_ROOT = 'api/{}'.format(API_VERSION)

urlpatterns = [
    path('photos/', PhotoSearchView.as_view()),
    path('photos/create/', PhotoCreateView.as_view()),
    path('photos/created/', TemplateView.as_view(
        template_name='photos/created.html')),
    path('photos/<slug:pk>/', PhotoDetailView.as_view(), name='photo-view'),
    path(API_ROOT + '/photos/', ApiPhotoSearchView.as_view()),
    # path(API_ROOT + '/photos/<slug:pk>/', ApiPhotoDetailView.as_view()),
]

photos/models.py
from django.contrib.gis.db import models
from django.core.validators import RegexValidator
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from wagtail.snippets.models import register_snippet
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.search import index
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.images.shortcuts import get_rendition_or_not_found
from collections import OrderedDict
from django.utils import timezone
import datetime
import re
import calendar
from taggit.models import TaggedItemBase
from taggit_selectize.managers import TaggableManager

DEFAULT_CREATED_AT = timezone.make_aware(datetime.datetime(1980, 1, 1))


def get_nw_string_from_point(point):
    '''Returns a nice string like this: '51.519°N 0.061°W'
    from a Point object SRID=4326;POINT (-0.06123 51.51981)
    '''
    if point is None:
        return ''

    y = [point.y, 'N']
    if y[0] < 0:
        y = [-y[0], 'S']
    x = [point.x, 'E']
    if x[0] < 0:
        x = [-x[0], 'W']

    ret = '{:.3f}°{} {:.3f}°{}'.format(y[0], y[1], x[0], x[1])
    return ret


@register_snippet
class PhotoFlag(models.Model):
    '''
    Represents a comment from a web user
    about the inappropriateness of a Photo record.
    '''
    photo = models.ForeignKey(
        'Photo', on_delete=models.CASCADE,
        related_name='flags'
    )
    flagger_comment = models.TextField(
        max_length=400,
        help_text='Please briefly tell us which exact parts of this web page'
        ' or photo are inappropriate and why you think they are.'
    )
    reviewer_comment = models.TextField(
        blank=True, null=True,
        help_text='Please provide: your name, the date, your opinion after'
        ' review and the action taken'
        ' (keep photo live or not, edited content).'
    )
    closed = models.BooleanField(
        'resolved', default=False,
        help_text='Tick to mark the review process complete'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Photo Flag #{}'.format(self.pk)

    panels = [
        FieldPanel('flagger_comment'),
        FieldPanel('reviewer_comment'),
        FieldPanel('closed'),
        SnippetChooserPanel('photo'),
    ]

    class Meta:
        ordering = ['-updated_at']
        verbose_name = 'Flag'
        verbose_name_plural = 'Flags'


@register_snippet
class PhotoCategory(index.Indexed, models.Model):
    label = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.label

    panels = [
        FieldPanel('label'),
    ]

    search_fields = [
        index.SearchField('label'),
    ]

    class Meta:
        ordering = ['label']
        verbose_name_plural = 'Photo Categories'


@register_snippet
class PhotoSubcategory(index.Indexed, models.Model):
    category = models.ForeignKey(PhotoCategory, on_delete=models.CASCADE)
    label = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60)

    def __str__(self):
        return '{}: {}'.format(self.category.label, self.label)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.label)
        super().save(*args, **kwargs)

    panels = [
        SnippetChooserPanel('category'),
        FieldPanel('label'),
    ]

    search_fields = [
        index.SearchField('label'),
    ]

    class Meta:
        ordering = ['category__label', 'label']
        unique_together = ['label', 'category']
        verbose_name_plural = 'Photo Subcategories'


@register_snippet
class Photographer(index.Indexed, models.Model):
    # optional - we keep those in case but NO LONGER NEEDED
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone_regex = RegexValidator(
        regex=r'^0\d{10}$',
        message=(
            'Phone number must be entered in the format: "01234567890"; '
            '11 digits allowed.'
        )
    )
    phone_number = models.CharField(
        validators=[phone_regex], max_length=11, blank=True, null=True
    )

    #
    AGE_RANGE_CHOICES = [
        (0, 'unspecified'),
        (1, '18 and under'),
        (2, '19-25'),
        (3, '26-45'),
        (4, '46-65'),
        (5, '66 and over'),
    ]

    age_range = models.PositiveSmallIntegerField(
        choices=AGE_RANGE_CHOICES,
        default=0
    )

    GENDER_CHOICES = [
        (1, 'female'),
        (2, 'male'),
        (0, 'prefer no to say'),
        (3, 'other'),
    ]

    gender_category = models.PositiveSmallIntegerField(
        choices=GENDER_CHOICES,
        default=0
    )
    gender_other = models.CharField(max_length=20, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering = ['last_name', 'first_name', 'email', 'phone_number']
        # unique_together = ['email', 'last_name', 'first_name']
        ordering = ['-created_at']

    def __str__(self):
        if self.last_name:
            return '{} {}'.format(self.first_name or '', self.last_name)
        return 'Photographer #{}'.format(self.pk)

    # Django admin is the preferred interface to manage photographers
    panels = [
        # FieldPanel('first_name'),
        # FieldPanel('last_name'),
        # FieldPanel('email'),
        # FieldPanel('phone_number'),
        FieldPanel('age_range'),
        FieldPanel('gender'),
    ]

    # Django admin is the preferred interface to manage photographers
    search_fields = [
        # index.SearchField('first_name', partial_match=True),
        # index.SearchField('last_name', partial_match=True),
        # index.SearchField('email', partial_match=True),
        # index.SearchField('phone_number', partial_match=True),
        # index.SearchField('age_range', partial_match=True),
        # index.SearchField('gender', partial_match=True),
    ]

    @classmethod
    def get_age_range_from_age(cls, age=None):
        '''e.g. get_age_range_from_age(20) => 2 i.e. (2, '19-25')'''
        if isinstance(age, str):
            m = re.match(r'^\d+', age)
            if m:
                age = int(m.group(0))
            else:
                age = ''

        if age is None or age == '':
            return 0

        ret = 2
        while True:
            if ret >= len(cls.AGE_RANGE_CHOICES):
                break
            age_min = int(re.findall(
                r'^\d+', cls.AGE_RANGE_CHOICES[ret][1])[0])
            if age < age_min:
                break
            ret += 1
        ret -= 1

        return ret

    def get_str_from_age_range(self):
        return dict(self.AGE_RANGE_CHOICES).get(self.age_range, '')

    @classmethod
    def get_age_range_from_str(cls, age_range_str):
        '''19-25 => 2'''
        return {s: n for n, s in cls.AGE_RANGE_CHOICES}[age_range_str]

    def get_str_from_gender(self):
        return dict(self.GENDER_CHOICES).get(self.gender, '')


class PhotoTag(TaggedItemBase):
    content_object = models.ForeignKey(
        'photos.Photo', on_delete=models.CASCADE,
        related_name='tagged_items'
    )


@register_snippet
class Photo(index.Indexed, models.Model):

    REVIEW_STATUS_SUBMITTING = -1
    REVIEW_STATUS_SUBMITTED = 0
    REVIEW_STATUS_PUBLIC = 1
    REVIEW_STATUS_ARCHIVED = 2
    REVIEW_STATUSES = (
        (REVIEW_STATUS_SUBMITTED, 'To be reviewed (not public)'),
        (REVIEW_STATUS_PUBLIC, 'Public'),
        (REVIEW_STATUS_ARCHIVED, 'Archived (not public)'),
        (REVIEW_STATUS_SUBMITTING, 'Incomplete submission'),
    )

    FEELING_POSITIVE = -1
    FEELING_NEUTRAL = 0
    FEELING_NEGATIVE = 1
    FEELINGS = (
        (FEELING_POSITIVE, 'Positive'),
        (FEELING_NEUTRAL, 'Neutral'),
        (FEELING_NEGATIVE, 'Negative'),
    )

    MONTHS = [(i + 1, name) for i, name in enumerate(calendar.month_name[1:])]

    photographer = models.ForeignKey(
        Photographer,
        on_delete=models.SET_NULL,
        null=True, blank=True, default=None
    )

    # public = models.BooleanField(default=False)
    # image = models.ImageField(upload_to='photos', blank=True, null=True)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='+'
    )

    legacy_categories = models.TextField(
        'Legacy categories, for reference only',
        blank=True, default=''
    )

    description = models.TextField(blank=True, default='')
    comments = models.TextField(
        'Internal comments', blank=True, null=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(auto_now=True)

    taken_year = models.IntegerField(
        'Year (photo content)', blank=True, null=True, default=None)
    taken_month = models.IntegerField(
        'Month (photo content)',
        choices=MONTHS,
        blank=True, null=True, default=None
    )
    taken_day = models.IntegerField(
        'Day (photo content)', blank=True, null=True, default=None
    )

    location = models.PointField(blank=True, null=True)

    review_status = models.IntegerField(choices=REVIEW_STATUSES, default=0)

    subcategories = models.ManyToManyField(PhotoSubcategory, blank=True)

    # data captured by the submission form
    author_focus_keywords = models.CharField(
        max_length=150,
        blank=True, null=True, default=None,
        help_text='Author\'s main focus in a few keywords'
    )
    author_focus = models.TextField(
        blank=True, default='', help_text='Author\'s main focus'
    )

photos/templates/photos/create-old.html
{% extends 'base.html' %}
{% load mmee_wagtail_tags staticfiles compress %}

{% block meta_title %}Upload a Photo{% endblock %}

{% block h1 %}{% endblock %}
{% block main %}
<div class="submission-form">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}

    {% if form.has_errors %}
        <div class="form-general-errors">
            Some fieds are invalid, please correct the errors and resubmit.
          {{ form.non_field_errors }}
        </div>
    {% endif %}

    <input id='step2' type='checkbox' aria-label="step 2">
    <input id='step3' type='checkbox' aria-label="step 3">

  <div id="part1" class="step">
    <h1>Submission form</h1>
      <div class='file-input'>
        {% form_field form.image_file accept="image/png, image/jpeg, image/jpg" aria_label="upload photo" autocomplete="off" %}
        <img id="upload-preview" alt="Image upload preview">
      </div>

      <hr>
      <h4>Date photo was taken</h4>
      <label class="photo-date">Month
          {% form_field form.taken_month %}
      </label>
      <label class="photo-date">Year
          {% form_field form.taken_year placeholder="e.g. 2019" %}
      </label>
      <hr>

      <h4>Location</h4>
      <p>Click the point on the map where the photo was taken. A blue circle will represent that location. Then drag & drop the circle to adjust the location.</p>
      <p>You can also <a href="javascript:geodjango_location.clearFeatures()">remove the circle</a> to start again.</p>
      {% form_field form.location %}

      {# step 2 #}
      <hr>

      {% form_field form.author_focus_keywords placeholder="" label="In five keywords or less, what is the main focus in the photo you took?" autocomplete="off" %}

      {# step 3 #}
      <hr>

      <fieldset>
        <legend><h4>How do you feel about this photo?</h4></legend>
        {% form_field form.author_feeling_category placeholder=""  %}
      </fieldset>
      <hr>

      {% form_field form.author_feeling_keywords placeholder="" label="In three keywords or less, describe that feeling." autocomplete="off" %}

      {# step 4 #}
      <hr>

      {% form_field form.author_reason placeholder="" label="Why did you take this photo?" autocomplete="off" %}

      {# step 5 #}
      <hr>

      <fieldset>
        <legend><h4>What age category are you?</h4></legend>
        {% form_field form.age_range placeholder="" %}
      </fieldset>
      <hr>

      <fieldset>
        <legend><h4>What do you identify as?</h4></legend>
        {% form_field form.gender placeholder="" %}
      </fieldset>

      {% form_field form.gender_other placeholder="" label="If other, please specify" autocomplete="off" %}
      <hr>
    <div class="button-wrapper">
      <a href="/"><label class="back">Cancel</label></a>
      <label for='step2' id="continue-step2" class="next">Next</label>
    </div>

  </div>

  <div id="part2" class="step">
      <h3>Consent Information</h3>
      <p>I understand that this image will only be used by Sensing Place,
      and by uploading this photograph and associated information,
      I confirm that this image and associated text will not cause any offence,
      embarrassment or distress. I understand that the image and/or text
      may not be made public if it seemed inappropriate by the moderators.
      By uploading this image and associated text, I give permission for
      Sensing Place to use them on their public website, and for research
      purposes related to this website.
      </p>

      {{ form.consent.errors }}
      <label>
          {% form_field form.consent class="show" %}
          I have read and accept the terms
      </label>

      <div class="button-wrapper">
        <label for='step2' id="back-step2" class="back">
          Back
        </label>
        <label id="continue-step3" class="next last" >
          Submit
          <input type="submit" value="Submit" name="Submit" class="hidden submit">
        </label>
      </div>
    </div>

  </form>

</div>
{% endblock main %}

{% block footer_scripts %}
    {{ block.super }}

    <script src="{% static 'exif-js/exif.js' %}"></script>
    <script>
    // TODO: move to js file
    $(function() {
        var $form = $('.submission-form > form');

        if (1) {
            $(document).on('click', '.next:not(:has(.submit))', function(e) {
                // Don't let user go to next step if invalid inputs in current
                // one
                var is_step_valid = 1;
                $(this).parents('.step').find(':input').each(function() {
                    is_step_valid &= this.checkValidity();
                });
                if (!is_step_valid) {
                    // this forces the browser to show the error messages
                    $form.find('.submit').click();
                    // we don't go to next step
                    e.preventDefault();
                    return false;
                }
            });
        }

        $preview = $('#upload-preview');
        $preview[0].addEventListener('load', image_loaded);

        function image_loaded() {
            $preview.addClass('show');

            var year = '';
            var month = 0;

            // https://github.com/exif-js/exif-js
            $preview[0].exifdata = null;
            EXIF.getData($preview[0], function() {
                var exif_data = EXIF.getAllTags($preview[0]);
                // console.log(exif_data);
                // DateTimeOriginal: "2018:12:20 21:15:59"
                var date = exif_data.DateTimeOriginal;
                if (date) {
                    date_parts = date.split(':');
                    year = date_parts[0];
                    month = parseInt(date_parts[1]);
                }

                // center map on Image GPS coordinates
                // also add a point there.
                var lon = exif_data.GPSLongitude;
                var lat = exif_data.GPSLatitude;
                var photo_location_is_working = true;
                geodjango_location.clearFeatures();
                if (photo_location_is_working && lat && lon) {
                    // deg, min, sec => float
                    var coord = [lon, lat].map(function(v) {
                        return parseFloat(v[0].toString())
                            + parseFloat(v[1].toString()) / 60.0
                            + parseFloat(v[2].toString()) / 60.0 / 60.0;
                    });
                    // coord = [1, 53]; coord = ol.proj.transform(coord, 'EPSG:4326', 'EPSG:3857'); geodjango_location.map.getView().setCenter(coord);
                    if (exif_data.GPSLongitudeRef == 'W') coord[0] = -coord[0];
                    if (exif_data.GPSLatitudeRef == 'S') coord[1] = -coord[1];
                    coord = ol.proj.transform(coord, 'EPSG:4326', 'EPSG:3857');
                    geodjango_location.map.getView().setCenter(coord);
                    geodjango_location.map.getView().setZoom(15);
                    geodjango_location.featureCollection.push(new ol.Feature({
                        geometry: new ol.geom.Point(coord)
                    }));
                }
            });

            $('#id_taken_year').val(year);
            $('#id_taken_month').val(month);
        };

        $('input[type=file]').change(function() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $preview.attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        });

    })
    </script>
{% endblock %}

photos/templates/photos/create.html
{% extends 'base.html' %}
{% load mmee_wagtail_tags staticfiles compress %}

{% block meta_title %}Upload a Photo{% endblock %}

{% block h1 %}{% endblock %}
{% block main %}
<p>As of 27 Nov 2024, this site no longer accept new photo submissions.
  <br>
  <a href="/">Return to the home page</a>
</p>
{% endblock %}

photos/templates/photos/created.html
{% extends 'base.html' %}

{% block main %}
<div class="submission-form">
  <div id="part1">
    <p>Your reference number: <strong>{{ request.session.reference_number }}</strong></p>

    <p>Thank you for submitting a photograph with associated text to
      Sensing Place. It will now go to moderation and until moderation is
      completed your photograph will not be made public. Photographs of
      identifiable people cannot be made public due to Data Protection
      legislation, and images and/or text that could cause offense,
      embarrassment or distress will also not be made public.
    </p>

    <p>Moderation will be done as soon as possible, and your photograph should
      be made public within a couple of weeks.
    </p>

    <p>If you would like to contact the moderators to check the progress of your
      photograph, please provide details on the uploaded photograph and the
      reference number above to sensingplace@winchester.ac.uk</p>
    </p>
  </div>
</div>
{% endblock main %}

photos/templates/photos/photo.html
{% extends 'base.html' %}
{% load wagtailimages_tags %}

{% block meta_title %}Photo: "{{photo.title}}"{% endblock %}

{% block title %}
  {% if photo.title %}
    "{{photo.title}}"
  {% else %}
    Photo details
  {% endif %}
{% endblock %}

{% block main %}
<main>

    {% if 0 %}
        <section id="search" aria-label="search">
            <form action="/photos/" class="search-field">
                <input type="text" name="phrase" value="{{ phrase }}" autocomplete="off">
                <button aria-label="Search" class="search-icon" type="submit"></button>
            </form>
        </section> <!-- end .search -->
    {% endif %}

    {% if photo_flag %}
        <p class="alert alert-success">
            Thank you for caring about the quality of our content.
            An editor will soon review your comment and take the
            appropriate action.
            {% if moderation_page %}
                <a href="{{ moderation_page.get_url }}" target="_blank">Moderation policy</a>
            {% endif %}
        </p>
    {% else %}
        <!-- The form for a visitor to flag a photo as inappropriate-->
        {% if 0 %}
            <form id="form-flag" class="form-flag" action="" method="POST">
                {% csrf_token %}
                {{ form_flag.non_field_errors }}

                {{ form_flag.flagger_comment.errors }}
                <p>{{ form_flag.flagger_comment.help_text }}
                    {% if moderation_page %}
                        <a href="{{ moderation_page.get_url }}" target="_blank">Moderation policy</a>
                    {% endif %}
                </p>
                {{ form_flag.flagger_comment }}
                <p>
                    <a href="#" class="form-cancel btn">Cancel</a>
                    <input type="submit" name="submit" value="Submit" class="form-submit btn">
                </p>
            </form>
        {% endif %}
    {% endif %}

    <section id="photo" aria-label="photo">
        <div class="photo-image">
          {% image photo.image height-700 height="" width="" %}
        </div> <!-- end #photo -->

        <div class="photo-data">
          {% if 0 and not photo_flag %}
              <p>
                  <a class="flag-button" href="#form-flag">
                    Report a problem with this photo
                  </a>
              </p>
          {% endif %}

          {% if photo.description %}
              <div class="photo-description">
                <h3>Description</h3>
                <p>
                  {{ photo.description }}
                </p>
              </div><!-- end #photo-description -->
          {% endif %}

          <div class="photo-photograph">
            {% if photo.taken_year %}
                <h3>Date</h3>
                  <ul>
                      {% if photo.taken_year %}
                            {{ photo.taken_month_name }}
                            {{ photo.taken_year }}
                      {% endif %}
                  </ul>
            {% endif %}
            {% with photo.subcategories.all as subcats %}
                {% if subcats %}
                    <h3>Categories</h3>
                    <ul>
                        {% for subcat in photo.subcategories.all %}
                            <li>{{ subcat }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
          </div><!-- end .photograph-data -->

          {% with photo.tags.all as tags %}
            {% if tags %}
              <div class="photo-tags">
                <h3>Tags</h3>
                <ul>
                    {% for tag in tags %}
                        <li><a href="/photos/?phrase={{tag}}">{{ tag }}</a></li>
                    {% endfor %}
                </ul>
              </div><!-- end .location -->
            {% endif %}
          {% endwith %}

          {% if photo.location %}
              <div class="photo-location">
                <h3>Location Coordinates</h3>
                <!-- TO: GN, could you add geolocation, lat/long here please -->
                <p>{{ photo.location_nw }}</p>

              </div><!-- end .location -->
          {% endif %}

        </div><!-- end .photo-data -->
    </section> <!-- end .photo -->

    <section id="photo-map" aria-label="photo map">
        <!-- img src="https://images.fineartamerica.com/images-medium-large-5/london-map-art-michael-tompsett.jpg" alt=""/ -->

        <h3>Map</h3>
        <!-- div instead of img -->
        {% if photo.location %}
            <div id="map-leaflet">
            </div>
        {% else %}
            <p>This photo has not yet been precisely located on a map</p>
        {% endif %}

    </section> <!-- end #map -->

</main>

{% endblock main %}

{% block footer_scripts %}
{{ block.super }}
<script>
// // no longer maintained
// TILE_URL = "http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png"
TILE_URL = "https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}.png"
$(function(){
    var map_id = 'map-leaflet';

    if (document.getElementById(map_id)) {
        // Create map and set view
        var photo_point = [{{ photo.location.y }}, {{ photo.location.x }}];
        var photomap = L.map(map_id).setView(photo_point, 15);
        // Create tilelayer and add to map
        var tileLayer = L.tileLayer(
            TILE_URL
        ).addTo(photomap);
        var sample_markers = [
          {'latlng':photo_point, 'content':"This Photo"}
        ];
        for (i in sample_markers){
          m = L.marker(sample_markers[i]['latlng']).bindPopup(
              sample_markers[i]['content']
          ).addTo(photomap);
        }
    }

    function show_form_flag(hide) {
        var $form_flag = $('#form-flag');
        $form_flag.toggle(!hide);
        if (!hide) {
            $form_flag.find('textarea').focus();
        }
    }

    $('.flag-button').on('click', function() {
        show_form_flag();
    });

    $('.form-cancel').on('click', function() {
        show_form_flag(1);
    });

    {% if form_flag.is_bound %}
        show_form_flag();
    {% endif %}
});
</script>
{% endblock %}